from pathlib import Path
p=Path('/home/ubuntu/vistoria-campo-pro/client/src/pages/Home.tsx')
s=p.read_text()
s=s.replace('  Activity,\n', '  Activity,\n  Camera,\n')
s=s.replace('  HardHat,\n', '  HardHat,\n  ImagePlus,\n')
s=s.replace('type Participant = { name: string; role: string };', 'type Participant = { name: string; role: string };\ntype Photo = { id: string; name: string; dataUrl: string; caption: string };')
s=s.replace('  categories: string[];\n  findings:', '  categories: string[];\n  photos: Photo[];\n  findings:')
s=s.replace('  categories: defaultSections,\n  notes:', '  categories: defaultSections,\n  photos: [],\n  notes:')
s=s.replace('  const participants = (raw.participants || []).map((participant) => typeof participant === "string" ? { name: participant, role: "" } : participant);\n  return { id:', '  const participants = (raw.participants || []).map((participant) => typeof participant === "string" ? { name: participant, role: "" } : participant);\n  const photos = raw.photos || [];\n  return { id:')
s=s.replace('status: raw.status || "Rascunho", notes: raw.notes || "", categories, findings };', 'status: raw.status || "Rascunho", notes: raw.notes || "", categories, photos, findings };')
s=s.replace('  categories: [...defaultSections],\n  findings:', '  categories: [...defaultSections],\n  photos: [],\n  findings:')
# Add photo handlers after participant handler.
s=s.replace('  const locate = () => {', '''  const addPhotos = (files: FileList | null) => { if (!files?.length) return; Array.from(files).forEach((file) => { if (!file.type.startsWith("image/")) return; const reader = new FileReader(); reader.onload = () => { const dataUrl = String(reader.result); setForm((current) => ({ ...current, photos: [...current.photos, { id: `photo-${Date.now()}-${Math.random().toString(16).slice(2)}`, name: file.name, dataUrl, caption: "" }] })); }; reader.readAsDataURL(file); }); toast.success(`${files.length} foto(s) adicionada(s).`); };\n  const updatePhoto = (id: string, patch: Partial<Photo>) => setForm((current) => ({ ...current, photos: current.photos.map((photo) => photo.id === id ? { ...photo, ...patch } : photo) }));\n  const removePhoto = (id: string) => setForm((current) => ({ ...current, photos: current.photos.filter((photo) => photo.id !== id) }));\n  const locate = () => {''')
# Add photo section after participant card.
needle='''</div><button type="button" onClick={() => update("participants", [...form.participants, { name: "", role: "" }])} className="mt-4 flex items-center gap-2 text-xs font-bold text-[#0f766e] hover:text-[#0b5a55]"><Plus size={15} /> Adicionar participante</button></section>'''
insert=needle+'''<section className="card-shadow rounded-2xl bg-white p-5 sm:p-7"><div className="mb-5 flex items-start justify-between"><div><h3 className="font-display text-lg font-bold text-[#263a3d]">Evidências fotográficas</h3><p className="mt-1 text-xs text-[#859497]">Tire fotos na hora ou selecione imagens da galeria.</p></div><Camera size={20} className="text-[#7e9999]" /></div><label className="flex cursor-pointer flex-col items-center justify-center rounded-xl border border-dashed border-[#bfded7] bg-[#f7fcfa] px-5 py-7 text-center transition hover:bg-[#eef8f4]"><span className="mb-3 flex h-11 w-11 items-center justify-center rounded-xl bg-[#e0f2ed] text-[#0f766e]"><ImagePlus size={21} /></span><span className="text-sm font-bold text-[#3d6262]">Adicionar fotos da vistoria</span><span className="mt-1 text-xs text-[#829496]">No celular, abre diretamente a câmera</span><input type="file" accept="image/*" capture="environment" multiple className="hidden" onChange={(event) => { addPhotos(event.target.files); event.currentTarget.value = ""; }} /></label>{form.photos.length > 0 && <div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-3">{form.photos.map((photo) => <div key={photo.id} className="overflow-hidden rounded-xl border border-[#e0eae7] bg-white"><div className="relative aspect-[4/3] bg-[#eef4f2]"><img src={photo.dataUrl} alt={photo.caption || photo.name} className="h-full w-full object-cover" /><button type="button" onClick={() => removePhoto(photo.id)} className="absolute right-2 top-2 rounded-lg bg-[#173b3b]/80 p-1.5 text-white hover:bg-[#c2413a]"><Trash2 size={13} /></button></div><input value={photo.caption} onChange={(event) => updatePhoto(photo.id, { caption: event.target.value })} className="w-full border-0 px-3 py-2 text-xs outline-none" placeholder="Legenda / local" /></div>)}</div>}</section>'''
if needle not in s: raise SystemExit('participant section anchor not found')
s=s.replace(needle, insert)
# Include photos in clean save explicitly.
s=s.replace('const clean = { ...form, status, participants:', 'const clean = { ...form, status, photos: form.photos, participants:')
# Report add evidence section before participant footer block.
report_anchor='''<div className="mt-10 grid gap-6 border-t border-[#e7eeec] pt-6 sm:grid-cols-2">'''
report_insert='''{visit.photos.length > 0 && <section className="mt-10 break-inside-avoid border-t border-[#e7eeec] pt-6"><div className="mb-4 flex items-center gap-2"><Camera size={16} className="text-[#0f766e]" /><h2 className="font-display text-base font-bold text-[#2e4346]">Evidências fotográficas</h2><span className="text-xs text-[#91a0a3]">{visit.photos.length} fotos</span></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{visit.photos.map((photo) => <figure key={photo.id} className="overflow-hidden rounded-lg border border-[#e4ecea]"><img src={photo.dataUrl} alt={photo.caption || photo.name} className="aspect-[4/3] w-full object-cover" /><figcaption className="px-2 py-2 text-[10px] text-[#617477]">{photo.caption || photo.name}</figcaption></figure>)}</div></section>}'''+report_anchor
if report_anchor not in s: raise SystemExit('report anchor not found')
s=s.replace(report_anchor, report_insert, 1)
p.write_text(s)
print('photos added')
