from pathlib import Path
import re
p=Path('/home/ubuntu/vistoria-campo-pro/client/src/pages/Home.tsx')
s=p.read_text()
if 'import { trpc } from "@/lib/trpc";' not in s:
    s=s.replace('import { toast } from "sonner";\n', 'import { toast } from "sonner";\nimport { trpc } from "@/lib/trpc";\n')
s=s.replace('export default function Home() {\n', 'export default function Home() {\n  const uploadImage = trpc.storage.uploadImage.useMutation();\n',1)
s=re.sub(r'  const addLogo = async \(file: File \| undefined\) => \{.*?\};\n  const addPhotos', '''  const addLogo = async (file: File | undefined) => { if (!file || !file.type.startsWith("image/")) return; try { const dataUrl = await compressImage(file, 800, 0.75); const uploaded = await uploadImage.mutateAsync({ fileName: file.name, contentType: "image/jpeg", dataUrl }); setForm((current) => ({ ...current, logoDataUrl: uploaded.url })); toast.success("Logo salva na nuvem."); } catch { toast.error("Não foi possível enviar a logo para a nuvem."); } };\n  const addPhotos''', s, count=1, flags=re.S)
s=re.sub(r'  const addPhotos = \(files: FileList \| null\) => \{.*?\};\n  const updatePhoto', '''  const addPhotos = (files: FileList | null) => { if (!files?.length) return; Array.from(files).filter((file) => file.type.startsWith("image/")).slice(0, 8).forEach(async (file) => { try { const dataUrl = await compressImage(file); const uploaded = await uploadImage.mutateAsync({ fileName: file.name, contentType: "image/jpeg", dataUrl }); setForm((current) => ({ ...current, photos: [...current.photos, { id: `photo-${Date.now()}-${Math.random().toString(16).slice(2)}`, name: file.name, dataUrl: uploaded.url, caption: "" }] })); } catch { toast.error(`Não foi possível enviar ${file.name} para a nuvem.`); } }); toast.success("Enviando fotos para a nuvem..."); };\n  const updatePhoto''', s, count=1, flags=re.S)
s=re.sub(r'  const addFindingPhoto = \(section: SectionKey, id: string, files: FileList \| null\) => \{.*?\};\n  const removeFindingPhoto', '''  const addFindingPhoto = (section: SectionKey, id: string, files: FileList | null) => { if (!files?.length) return; Array.from(files).slice(0, 4).forEach(async (file) => { if (!file.type.startsWith("image/")) return; try { const dataUrl = await compressImage(file); const uploaded = await uploadImage.mutateAsync({ fileName: file.name, contentType: "image/jpeg", dataUrl }); setForm((current) => ({ ...current, findings: { ...current.findings, [section]: (current.findings[section] || []).map((item) => item.id === id ? { ...item, photos: [...(item.photos || []), { id: `item-photo-${Date.now()}-${Math.random().toString(16).slice(2)}`, name: file.name, dataUrl: uploaded.url, caption: "" }] } : item) } })); toast.success("Foto salva na nuvem e vinculada ao item."); } catch { toast.error("Não foi possível enviar a foto para a nuvem."); } }); };\n  const removeFindingPhoto''', s, count=1, flags=re.S)
p.write_text(s)
print('cloud upload connected')
