from pathlib import Path
p=Path('/home/ubuntu/vistoria-campo-pro/client/src/pages/Home.tsx')
s=p.read_text()
# Add executive report styles for print and on-screen preview.
style='''\n.executive-cover { background: linear-gradient(135deg, #0c4542 0%, #126b62 58%, #1b8878 100%); }\n.executive-kicker { letter-spacing: .22em; font-size: 10px; font-weight: 800; text-transform: uppercase; }\n.executive-label { letter-spacing: .14em; font-size: 10px; font-weight: 800; text-transform: uppercase; }\n'''
css=Path('/home/ubuntu/vistoria-campo-pro/client/src/index.css')
ct=css.read_text()
if '.executive-cover' not in ct: css.write_text(ct+style)
# Replace report cover top branding/headline block.
old='''<div className="border-b-[6px] border-[#f6b73c] bg-[#173b3b] px-6 py-7 text-white sm:px-10"><div className="flex flex-col justify-between gap-6 sm:flex-row sm:items-start"><div><div className="mb-5 flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#f6b73c] text-[#173b3b]"><ClipboardCheck size={22} /></div><div><div className="font-display text-sm font-bold">Vistoria<span className="text-[#f6b73c]">.pro</span></div><div className="text-[9px] font-bold uppercase tracking-[.16em] text-[#a9c5c2]">Relatório de campo</div></div></div><p className="mb-2 text-[10px] font-bold uppercase tracking-[.18em] text-[#8eb0ad]">Rodada técnica operacional</p><h1 className="font-display text-3xl font-bold leading-tight sm:text-4xl">{visit.property || "Vistoria sem identificação"}</h1><p className="mt-2 text-sm text-[#b7cfca]">ID da operação {visit.code || "—"} · {visit.location || "Local não informado"}</p></div><div className="sm:text-right"><div className="inline-flex rounded-full bg-[#d9f2e5] px-3 py-1.5 text-xs font-extrabold text-[#176440]">{visit.status}</div><p className="mt-3 text-xs text-[#a9c5c2]">Data da visita</p><p className="font-display text-lg font-bold">{formatDate(visit.date)}</p></div></div></div>'''
new='''<div className="executive-cover border-b-[7px] border-[#f6c453] px-6 py-8 text-white sm:px-10"><div className="flex flex-col justify-between gap-8 sm:flex-row sm:items-start"><div className="max-w-2xl"><div className="mb-8 flex items-center gap-3"><div className="flex h-12 w-12 items-center justify-center rounded-xl bg-[#f6c453] text-[#103e3b] shadow-lg"><ClipboardCheck size={25} strokeWidth={2.5} /></div><div><div className="font-display text-base font-bold tracking-tight">NOME DA EMPRESA</div><div className="executive-label mt-1 text-[#b9e0d6]">Unidade · Operações de campo</div></div></div><p className="executive-kicker mb-3 text-[#f6c453]">RELATÓRIO EXECUTIVO DE CAMPO</p><h1 className="font-display text-3xl font-bold uppercase leading-[1.05] tracking-tight sm:text-5xl">RODADA TÉCNICA<br />OPERACIONAL</h1><p className="mt-4 text-sm font-bold uppercase tracking-[.18em] text-[#d4ece5]">INSPEÇÃO SEMANAL · {visit.property || "UNIDADE OPERACIONAL"}</p><p className="mt-3 max-w-xl text-sm leading-relaxed text-[#b9d8d1]">Avaliação integrada de segurança, qualidade, produtividade, custos e oportunidades de melhoria.</p></div><div className="sm:min-w-[170px] sm:text-right"><div className="mb-4 inline-flex rounded-full bg-[#d9f2e5] px-3 py-1.5 text-xs font-extrabold text-[#176440]">{visit.status.toUpperCase()}</div><p className="executive-label text-[#a9cec6]">DATA DA VISITA</p><p className="font-display text-xl font-bold">{formatDate(visit.date)}</p><p className="mt-4 executive-label text-[#a9cec6]">CÓDIGO</p><p className="font-display text-xl font-bold">#{visit.code || "—"}</p></div></div></div>'''
if old not in s: raise SystemExit('cover block not found')
s=s.replace(old,new,1)
# Add an executive summary line before metadata.
oldmeta='''<div className="grid border-b border-[#e8eeee] sm:grid-cols-3"><ReportMeta label="Equipe" value={visit.team || "Não informada"} icon={HardHat} /><ReportMeta label="Participantes" value={`${visit.participants.filter((participant) => participant.name.trim()).length} pessoas`} icon={Users} /><ReportMeta label="Itens avaliados" value={`${allItems.length} registros`} icon={ClipboardCheck} /></div>'''
newmeta='''<div className="border-b border-[#e8eeee] bg-[#f5faf8] px-6 py-4 sm:px-10"><div className="flex flex-wrap items-center gap-x-5 gap-y-2 text-xs text-[#5b7374]"><span><strong className="text-[#35595a]">EMPRESA:</strong> NOME DA EMPRESA</span><span><strong className="text-[#35595a]">EQUIPE:</strong> {visit.team || "NÃO INFORMADA"}</span><span><strong className="text-[#35595a]">LOCAL:</strong> {visit.location || "NÃO INFORMADO"}</span></div></div><div className="grid border-b border-[#e8eeee] sm:grid-cols-3"><ReportMeta label="Equipe" value={visit.team || "Não informada"} icon={HardHat} /><ReportMeta label="Participantes" value={`${visit.participants.filter((participant) => participant.name.trim()).length} pessoas`} icon={Users} /><ReportMeta label="Itens avaliados" value={`${allItems.length} registros`} icon={ClipboardCheck} /></div>'''
if oldmeta not in s: raise SystemExit('meta block not found')
s=s.replace(oldmeta,newmeta,1)
# Improve KPI heading before cards.
s=s.replace('<div className="p-6 sm:p-10"><div className="mb-8 grid gap-4 sm:grid-cols-3">', '<div className="p-6 sm:p-10"><div className="mb-5"><p className="executive-kicker text-[#0f766e]">VISÃO GERENCIAL</p><h2 className="mt-1 font-display text-lg font-bold uppercase text-[#2e4346]">Resumo executivo da inspeção</h2></div><div className="mb-8 grid gap-4 sm:grid-cols-3">',1)
# Footer institutional.
s=s.replace('<span>Vistoria Campo Pro · Documento operacional interno</span><span>Relatório {visit.code ? `#${visit.code}` : "sem ID"}</span>', '<span>NOME DA EMPRESA · Documento de gestão operacional</span><span>RELATÓRIO {visit.code ? `#${visit.code}` : "SEM ID"} · USO INTERNO</span>',1)
p.write_text(s)
print('executive report updated')
