from pathlib import Path
import re
p=Path('/home/ubuntu/vistoria-campo-pro/client/src/pages/Home.tsx')
s=p.read_text()
# Insert browser-side image compression helper before Home component.
anchor='export default function Home() {'
helper='''const compressImage = (file: File, maxSize = 1280, quality = 0.68): Promise<string> => new Promise((resolve, reject) => { const reader = new FileReader(); reader.onerror = () => reject(reader.error); reader.onload = () => { const image = new Image(); image.onload = () => { const scale = Math.min(1, maxSize / Math.max(image.width, image.height)); const canvas = document.createElement("canvas"); canvas.width = Math.max(1, Math.round(image.width * scale)); canvas.height = Math.max(1, Math.round(image.height * scale)); const context = canvas.getContext("2d"); if (!context) return reject(new Error("Canvas indisponível")); context.drawImage(image, 0, 0, canvas.width, canvas.height); resolve(canvas.toDataURL("image/jpeg", quality)); }; image.onerror = () => reject(new Error("Imagem inválida")); image.src = String(reader.result); }; reader.readAsDataURL(file); });\n\n'''
if helper not in s: s=s.replace(anchor,helper+anchor)
# Replace addLogo with compressed async version.
s=re.sub(r'  const addLogo = \(file: File \| undefined\) => \{.*?\};\n  const addPhotos', '''  const addLogo = async (file: File | undefined) => { if (!file || !file.type.startsWith("image/")) return; try { const dataUrl = await compressImage(file, 800, 0.75); setForm((current) => ({ ...current, logoDataUrl: dataUrl })); } catch { toast.error("Não foi possível carregar a logo."); } };\n  const addPhotos''', s, count=1, flags=re.S)
# Replace addPhotos body.
s=re.sub(r'  const addPhotos = \(files: FileList \| null\) => \{.*?\};\n  const updatePhoto', '''  const addPhotos = (files: FileList | null) => { if (!files?.length) return; Array.from(files).filter((file) => file.type.startsWith("image/")).slice(0, 8).forEach(async (file) => { try { const dataUrl = await compressImage(file); setForm((current) => ({ ...current, photos: [...current.photos, { id: `photo-${Date.now()}-${Math.random().toString(16).slice(2)}`, name: file.name, dataUrl, caption: "" }] })); } catch { toast.error(`Não foi possível carregar ${file.name}.`); } }); toast.success(`${Math.min(files.length, 8)} foto(s) adicionada(s).`); };\n  const updatePhoto''', s, count=1, flags=re.S)
# Replace finding photo handler.
s=re.sub(r'  const addFindingPhoto = \(section: SectionKey, id: string, files: FileList \| null\) => \{.*?\};\n  const removeFindingPhoto', '''  const addFindingPhoto = (section: SectionKey, id: string, files: FileList | null) => { if (!files?.length) return; Array.from(files).slice(0, 4).forEach(async (file) => { if (!file.type.startsWith("image/")) return; try { const dataUrl = await compressImage(file); setForm((current) => ({ ...current, findings: { ...current.findings, [section]: (current.findings[section] || []).map((item) => item.id === id ? { ...item, photos: [...(item.photos || []), { id: `item-photo-${Date.now()}-${Math.random().toString(16).slice(2)}`, name: file.name, dataUrl, caption: "" }] } : item) } })); toast.success("Foto vinculada ao item."); } catch { toast.error("Não foi possível carregar a foto."); } }); };\n  const removeFindingPhoto''', s, count=1, flags=re.S)
# Replace unsafe persistence effect with guarded version.
s=s.replace('useEffect(() => { localStorage.setItem("vistoria-campo-pro-visits", JSON.stringify(visits)); }, [visits]);', '''useEffect(() => { try { localStorage.setItem("vistoria-campo-pro-visits", JSON.stringify(visits)); } catch { try { const compact = visits.map((visit) => ({ ...visit, photos: [], findings: Object.fromEntries(Object.entries(visit.findings).map(([key, items]) => [key, items.map((item) => ({ ...item, photos: [] }))])) })); localStorage.setItem("vistoria-campo-pro-visits", JSON.stringify(compact)); toast.warning("Armazenamento local cheio. As fotos continuam visíveis nesta sessão; reduza a quantidade de imagens para manter tudo salvo no aparelho."); } catch { toast.error("Não foi possível salvar a vistoria neste aparelho."); } } }, [visits]);''')
p.write_text(s)
print('storage quota safeguards applied')
