from pathlib import Path
p=Path('/home/ubuntu/vistoria-campo-pro/client/src/pages/Home.tsx')
s=p.read_text()
# Generic evidence area: retain camera capture and add a separate gallery picker.
s=s.replace('''<label className="flex cursor-pointer flex-col items-center justify-center rounded-xl border border-dashed border-[#bfded7] bg-[#f7fcfa] px-5 py-7 text-center transition hover:bg-[#eef8f4]"><span className="mb-3 flex h-11 w-11 items-center justify-center rounded-xl bg-[#e0f2ed] text-[#0f766e]"><ImagePlus size={21} /></span><span className="text-sm font-bold text-[#3d6262]">Adicionar fotos da vistoria</span><span className="mt-1 text-xs text-[#829496]">No celular, abre diretamente a câmera</span><input type="file" accept="image/*" capture="environment" multiple className="hidden" onChange={(event) => { addPhotos(event.target.files); event.currentTarget.value = ""; }} /></label>''','''<div className="grid gap-3 sm:grid-cols-2"><label className="flex cursor-pointer items-center justify-center gap-3 rounded-xl border border-[#0f766e] bg-[#0f766e] px-4 py-4 text-center text-white transition hover:bg-[#0b615b]"><Camera size={20} /><span><strong className="block text-sm">Tirar foto</strong><small className="text-[11px] text-[#c8ece4]">Abrir câmera do celular</small></span><input type="file" accept="image/*" capture="environment" multiple className="hidden" onChange={(event) => { addPhotos(event.target.files); event.currentTarget.value = ""; }} /></label><label className="flex cursor-pointer items-center justify-center gap-3 rounded-xl border border-[#cfe3de] bg-[#f7fcfa] px-4 py-4 text-center text-[#276c67] transition hover:bg-[#eaf7f3]"><ImagePlus size={20} /><span><strong className="block text-sm">Escolher da galeria</strong><small className="text-[11px] text-[#78918f]">Selecionar fotos existentes</small></span><input type="file" accept="image/*" multiple className="hidden" onChange={(event) => { addPhotos(event.target.files); event.currentTarget.value = ""; }} /></label></div>''')
# Item-level evidence: add gallery picker next to camera button.
s=s.replace('''</label><select value={item.status}''','''</label><label title="Escolher foto da galeria" className="flex h-[43px] w-[43px] cursor-pointer items-center justify-center rounded-lg border border-[#cfe3de] bg-[#f7fbfa] text-[#3e7b74] hover:bg-[#e7f5f0]"><ImagePlus size={17} /><input type="file" accept="image/*" multiple className="hidden" onChange={(event) => { addFindingPhoto(activeSection, item.id, event.target.files); event.currentTarget.value = ""; }} /></label><select value={item.status}''',1)
# Stronger executive cover geometry.
s=s.replace('className="executive-cover border-b-[7px] border-[#f6c453] px-6 py-8 text-white sm:px-10"','className="executive-cover relative overflow-hidden border-b-[9px] border-[#f6c453] px-6 py-8 text-white shadow-[inset_0_-18px_0_rgba(0,0,0,.08)] sm:px-10"',1)
s=s.replace('''<div className="flex flex-col justify-between gap-8 sm:flex-row sm:items-start">''','''<div className="pointer-events-none absolute -right-20 -top-24 h-72 w-72 rounded-full border-[28px] border-[#5cc6ad]/20" /><div className="pointer-events-none absolute -bottom-36 right-28 h-80 w-80 rounded-full border-[18px] border-[#f6c453]/15" /><div className="relative flex flex-col justify-between gap-8 sm:flex-row sm:items-start">''',1)
p.write_text(s)
css=Path('/home/ubuntu/vistoria-campo-pro/client/src/index.css')
ct=css.read_text()
ct=ct.replace('.executive-cover { background: linear-gradient(135deg, #0c4542 0%, #126b62 58%, #1b8878 100%); }','.executive-cover { background: linear-gradient(120deg, #073d3a 0%, #0d625b 42%, #15947f 100%); }')
css.write_text(ct)
print('gallery and header upgraded')
